[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
build_flags =
    -Iapp
    -Ibms_core
    -Ibms_hal
    -Ibms_platform/esp32
build_src_filter =
    +<app/*.cpp>
    +<bms_core/*.cpp>
    +<bms_platform/esp32/*.cpp>
