#ifndef BMS_FAULT_CODES_H
#define BMS_FAULT_CODES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    BMS_FAULT_CODE_NONE = 0x0000U,
    BMS_FAULT_CODE_CELL_OVERVOLTAGE = 0x1001U,
    BMS_FAULT_CODE_CELL_UNDERVOLTAGE = 0x1002U,
    BMS_FAULT_CODE_PACK_OVERVOLTAGE = 0x1003U,
    BMS_FAULT_CODE_PACK_UNDERVOLTAGE = 0x1004U,
    BMS_FAULT_CODE_DISCHARGE_OVERCURRENT = 0x2002U,
    BMS_FAULT_CODE_CURRENT_SENSOR_FAULT = 0x2003U,
    BMS_FAULT_CODE_CELL_TEMPERATURE_HIGH = 0x3001U,
    BMS_FAULT_CODE_TEMPERATURE_SENSOR_FAULT = 0x3003U,
    BMS_FAULT_CODE_ADC_READ_FAILURE = 0x4001U,
    BMS_FAULT_CODE_MEASUREMENT_INVALID = 0x4002U
} bms_fault_code_t;

enum {
    BMS_WARNING_CELL_LOW = (1UL << 0),
    BMS_WARNING_CELL_HIGH = (1UL << 1),
    BMS_WARNING_CELL_IMBALANCE = (1UL << 2),
    BMS_WARNING_OVERCURRENT = (1UL << 3),
    BMS_WARNING_TEMPERATURE_HIGH = (1UL << 4),
    BMS_WARNING_SENSOR_INVALID = (1UL << 5)
};

enum {
    BMS_FAULT_CELL_UNDERVOLTAGE = (1UL << 0),
    BMS_FAULT_CELL_OVERVOLTAGE = (1UL << 1),
    BMS_FAULT_PACK_UNDERVOLTAGE = (1UL << 2),
    BMS_FAULT_PACK_OVERVOLTAGE = (1UL << 3),
    BMS_FAULT_OVERCURRENT = (1UL << 4),
    BMS_FAULT_TEMPERATURE_HIGH = (1UL << 5),
    BMS_FAULT_SENSOR_INVALID = (1UL << 6)
};

typedef enum {
    BMS_VOLTAGE_THRESHOLD_CELL_LOW_WARNING_MV = 0,
    BMS_VOLTAGE_THRESHOLD_CELL_LOW_FAULT_MV,
    BMS_VOLTAGE_THRESHOLD_CELL_HIGH_WARNING_MV,
    BMS_VOLTAGE_THRESHOLD_CELL_HIGH_FAULT_MV,
    BMS_VOLTAGE_THRESHOLD_PACK_LOW_FAULT_MV,
    BMS_VOLTAGE_THRESHOLD_PACK_HIGH_FAULT_MV,
    BMS_VOLTAGE_THRESHOLD_CELL_IMBALANCE_WARNING_MV
} bms_voltage_threshold_index_t;

typedef enum {
    BMS_CURRENT_THRESHOLD_OVERCURRENT_WARNING_MA = 0,
    BMS_CURRENT_THRESHOLD_OVERCURRENT_FAULT_MA
} bms_current_threshold_index_t;

typedef enum {
    BMS_TEMPERATURE_THRESHOLD_HIGH_WARNING_DC = 0,
    BMS_TEMPERATURE_THRESHOLD_HIGH_FAULT_DC
} bms_temperature_threshold_index_t;

#ifdef __cplusplus
}
#endif

#endif
