#ifndef BMS_MEASUREMENT_CONFIG_H
#define BMS_MEASUREMENT_CONFIG_H

#include <stdint.h>

#include "bms_types.h"

#ifndef BMS_MEASUREMENT_BACKEND_REAL_ADC
#define BMS_MEASUREMENT_BACKEND_REAL_ADC 1
#endif

#define BMS_VOLTAGE_MODE_DIRECT_CELL (0U)
#define BMS_VOLTAGE_MODE_CUMULATIVE_TAPS (1U)

#include "bms_board_config.h"

#if defined(BMS_BOARD_PROFILE_REQUIRES_INA226_BACKEND)
#error "BMS_BOARD_PROTOTYPE0_PROFILE1 is reserved for the future INA226 backend."
#endif

#ifndef BMS_VOLTAGE_INPUT_MODE
#ifdef BMS_BOARD_VOLTAGE_INPUT_MODE
#define BMS_VOLTAGE_INPUT_MODE BMS_BOARD_VOLTAGE_INPUT_MODE
#else
#define BMS_VOLTAGE_INPUT_MODE BMS_VOLTAGE_MODE_CUMULATIVE_TAPS
#endif
#endif

#ifndef BMS_NTC_TO_GROUND
#define BMS_NTC_TO_GROUND 1
#endif

#ifndef BMS_ADC_LOW_VALID_MV
#define BMS_ADC_LOW_VALID_MV (20U)
#endif

#ifndef BMS_ADC_HIGH_VALID_MV
#define BMS_ADC_HIGH_VALID_MV (3250U)
#endif

#ifndef BMS_BOARD_HAS_VOLTAGE_CONFIG
static const uint32_t BMS_DEFAULT_VOLTAGE_DIVIDER_RATIO_PPM[BMS_NUM_CELLS] = {
    1132427UL,
    2625637UL,
    3959707UL,
    5293902UL,
    7340122UL,
    7705690UL,
};

static const int32_t BMS_DEFAULT_VOLTAGE_GAIN_PPM[BMS_NUM_CELLS] = {
    1000000L,
    1000000L,
    1000000L,
    1000000L,
    1000000L,
    1000000L,
};

static const int32_t BMS_DEFAULT_VOLTAGE_OFFSET_MV[BMS_NUM_CELLS] = {
    0L,
    0L,
    0L,
    0L,
    0L,
    0L,
};
#endif

#ifndef BMS_CURRENT_ZERO_MV
#define BMS_CURRENT_ZERO_MV (1650.0f)
#endif

#ifndef BMS_CURRENT_SHUNT_OHM
#define BMS_CURRENT_SHUNT_OHM (0.00025f)
#endif

#ifndef BMS_CURRENT_INA_GAIN
#define BMS_CURRENT_INA_GAIN (38.30f)
#endif

#ifndef BMS_CURRENT_ADC_HIGH_VALID_MV
#define BMS_CURRENT_ADC_HIGH_VALID_MV (3200U)
#endif

#ifndef BMS_CURRENT_ADC_GAIN_CORRECTION
#define BMS_CURRENT_ADC_GAIN_CORRECTION (1.0f)
#endif

#ifndef BMS_CURRENT_ADC_OFFSET_MV
#define BMS_CURRENT_ADC_OFFSET_MV (0.0f)
#endif

#ifndef BMS_CURRENT_READING_GAIN
#define BMS_CURRENT_READING_GAIN (1.000000f)
#endif

#ifndef BMS_CURRENT_SMOOTH_ALPHA
#define BMS_CURRENT_SMOOTH_ALPHA (0.060f)
#endif

#ifndef BMS_CURRENT_NOLOAD_ENTER_MA
#define BMS_CURRENT_NOLOAD_ENTER_MA (2000L)
#endif

#ifndef BMS_CURRENT_NOLOAD_EXIT_MA
#define BMS_CURRENT_NOLOAD_EXIT_MA (1300L)
#endif

#ifndef BMS_CURRENT_GAIN_CORRECTION
#define BMS_CURRENT_GAIN_CORRECTION BMS_CURRENT_READING_GAIN
#endif

#ifndef BMS_CURRENT_OFFSET_MA
#define BMS_CURRENT_OFFSET_MA (0.0f)
#endif

#ifndef BMS_NTC_SUPPLY_MV
#define BMS_NTC_SUPPLY_MV (3300.0f)
#endif

#ifndef BMS_NTC_FIXED_RESISTOR_OHM
#define BMS_NTC_FIXED_RESISTOR_OHM (10000.0f)
#endif

#ifndef BMS_NTC_NOMINAL_RESISTANCE_OHM
#define BMS_NTC_NOMINAL_RESISTANCE_OHM (10000.0f)
#endif

#ifndef BMS_NTC_BETA
#define BMS_NTC_BETA (3435.0f)
#endif

#ifndef BMS_NTC_NOMINAL_TEMP_K
#define BMS_NTC_NOMINAL_TEMP_K (298.15f)
#endif

#ifndef BMS_NTC_MIN_VALID_OHM
#define BMS_NTC_MIN_VALID_OHM (500.0f)
#endif

#ifndef BMS_NTC_MAX_VALID_OHM
#define BMS_NTC_MAX_VALID_OHM (200000.0f)
#endif

#ifndef BMS_TEMP_SENSOR_MIN_VALID_DC
#define BMS_TEMP_SENSOR_MIN_VALID_DC (-200)
#endif

#ifndef BMS_TEMP_SENSOR_MAX_VALID_DC
#define BMS_TEMP_SENSOR_MAX_VALID_DC (1000)
#endif

#define BMS_TEMPERATURE_INVALID_DC ((int16_t)-32768)

#ifndef BMS_BOARD_HAS_NTC_ADC_CALIBRATION
static const int32_t BMS_NTC_ADC_GAIN_PPM[BMS_NUM_TEMPERATURES] = {
    1000000L,
    1000000L,
    1000000L,
    1000000L,
};

static const int16_t BMS_NTC_ADC_OFFSET_MV[BMS_NUM_TEMPERATURES] = {
    0,
    0,
    0,
    0,
};
#endif

#endif
