#ifndef BMS_TYPES_H
#define BMS_TYPES_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BMS_CONTEXT_MAGIC (0x424D5330UL)
#define BMS_CONFIG_VERSION (2UL)
#define BMS_NUM_CELLS (6U)
#define BMS_NUM_TEMPERATURES (4U)
#define BMS_ACQ_CHANNEL_COUNT (BMS_NUM_CELLS + BMS_NUM_TEMPERATURES + 1U)
#define BMS_THRESHOLD_COUNT (8U)
#define BMS_SAMPLE_PERIOD_COUNT (8U)
#define BMS_CALIBRATION_CHANNEL_COUNT (BMS_ACQ_CHANNEL_COUNT)

typedef enum {
    BMS_SYSTEM_MODE_BOOT_INIT = 0,
    BMS_SYSTEM_MODE_WAKE_RESTORE,
    BMS_SYSTEM_MODE_ACTIVE_MONITORING,
    BMS_SYSTEM_MODE_IDLE_MONITORING,
    BMS_SYSTEM_MODE_SLEEP_READY,
    BMS_SYSTEM_MODE_SLEEP_MODE,
    BMS_SYSTEM_MODE_DIAGNOSTIC_MODE,
    BMS_SYSTEM_MODE_FAULT_ACTIVE,
    BMS_SYSTEM_MODE_SAFE_MONITORING
} bms_system_mode_t;

typedef enum {
    BMS_WAKE_CAUSE_UNKNOWN = 0,
    BMS_WAKE_CAUSE_POWER_ON,
    BMS_WAKE_CAUSE_TIMER,
    BMS_WAKE_CAUSE_UART,
    BMS_WAKE_CAUSE_GPIO,
    BMS_WAKE_CAUSE_FAULT_ALERT,
    BMS_WAKE_CAUSE_LOAD_OR_CHARGER
} bms_wake_cause_t;

typedef enum {
    BMS_SCHEDULER_STOPPED = 0,
    BMS_SCHEDULER_ACTIVE,
    BMS_SCHEDULER_IDLE,
    BMS_SCHEDULER_SLEEP_WINDOW
} bms_scheduler_status_t;

typedef enum {
    BMS_SOC_METHOD_NOT_AVAILABLE = 0,
    BMS_SOC_METHOD_VOLTAGE_ONLY,
    BMS_SOC_METHOD_COULOMB_COUNTING,
    BMS_SOC_METHOD_HYBRID
} bms_soc_method_t;

typedef enum {
    BMS_SOH_NOT_AVAILABLE = 0,
    BMS_SOH_BASIC_CAPACITY_BASED,
    BMS_SOH_RESISTANCE_TREND_BASED,
    BMS_SOH_MODEL_BASED
} bms_soh_method_t;

typedef enum {
    BMS_FAULT_SEVERITY_NONE = 0,
    BMS_FAULT_SEVERITY_INFO,
    BMS_FAULT_SEVERITY_WARNING,
    BMS_FAULT_SEVERITY_LIMITING,
    BMS_FAULT_SEVERITY_CRITICAL
} bms_fault_severity_t;

typedef enum {
    BMS_SLEEP_DECISION_NOT_EVALUATED = 0,
    BMS_SLEEP_DECISION_ALLOWED,
    BMS_SLEEP_DECISION_DENIED
} bms_sleep_decision_t;

typedef enum {
    BMS_SLEEP_REASON_NOT_EVALUATED = 0,
    BMS_SLEEP_REASON_ALLOWED,
    BMS_SLEEP_REASON_DENIED_LOAD_ACTIVE,
    BMS_SLEEP_REASON_DENIED_FAULT_ACTIVE
} bms_sleep_reason_t;

#ifdef __cplusplus
}
#endif

#endif
