#ifndef BMS_PROTOTYPE0_PROFILE1_H
#define BMS_PROTOTYPE0_PROFILE1_H

#define BMS_BOARD_NAME "BMS_BOARD_PROTOTYPE0_PROFILE1"
#define BMS_BOARD_PROFILE_ID (1U)
#define BMS_CURRENT_SENSOR_TYPE BMS_CURRENT_SENSOR_INA226
#define BMS_BOARD_PROFILE_REQUIRES_INA226_BACKEND 1

#define BMS_INA226_I2C_ADDRESS (0x40U)
#define BMS_INA226_SHUNT_OHM (0.00025f)
#define BMS_INA226_MAX_EXPECTED_CURRENT_MA (120000L)

#include "../prototype0_common/bms_prototype0_common.h"

#endif
